<?php

namespace SayHiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupsRepository extends EntityRepository
{
}
