<?php

namespace SayHiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function showAllLike($name){
        $query =$this->getEntityManager()->createQuery(''
                . 'SELECT u FROM SayHiBundle:User u WHERE u.name LIKE :name')
                ->setParameter('name', '%'.$name.'%');
        return $query->getResult();
    }
}
